language: python
python:
  - "2.7"
install:
  - "sudo apt-get install haskell-platform texlive"
  - "cabal update"
  - "cabal install pandoc --reinstall --force-reinstalls --constraint=transformers==0.3.0.0"
  - "pip install -r requirements.txt"

script:
  - "PATH=$HOME/.cabal/bin/:$PATH make"
